# Generated by Django 5.0.6 on 2024-06-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_toto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toto',
        ),
    ]
